package com.example.period_app_01.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.time.LocalDate

/*
 * entity class defines a table, each instance of the class is a row in the table
 * au such, each row has its own instance variables (e.g. id and date)
 * mapping to SQLite table in the database
 */
@Entity(tableName = "dates")
// for data class, obligatory methods are automatically generated by the compiler
data class Dates(
    // to distinguish individual entries in table, requires declaration and initialization of value
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    // 月经开始日期
    val date: LocalDate?,
    // 月经结束日期
    val endDate: LocalDate? = null,
    //
    val period: Long = 0
)